### ISSUE TITLE
HoloLens 2 emulator GPU acceleration not working

### ISSUE THREAD

**Issue by ArmsOfSorrow** [MicrosoftDocs/mixed-reality#1687] opened 2019-10-10 18:27 UTC
[Enter feedback here]
I'm unable to get GPU acceleration to work with the HoloLens 2 emulator (18362.1034). My GPU is an AMD Radeon RX580, which one could assume should be sufficiently powerful for the task. However, the diagnostics tab in the settings says "The GPU is not running: Problem code: 43". I didn't find anything on the internet really referring to the same problem.
My Windows build is 18362.10022.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0051f2fd-9bcd-7eb8-48f0-b8b170d42a49
* Version Independent ID: 2c1a0a2b-6a3f-1a1d-caf1-4a06caf5411b
* Content: [Using the HoloLens Emulator - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-hololens-emulator#feedback)
* Content Source: [mixed-reality-docs/using-the-hololens-emulator.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/using-the-hololens-emulator.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @pbarnettms
* Microsoft Alias: **pbarnett**

**Comment by pbarnettms** [comment] 2019-10-10 19:04
@ArmsOfSorrow Have you tried installing the latest RX580 drivers on your PC from https://www.amd.com/en/support/graphics/radeon-500-series/radeon-rx-500-series/radeon-rx-580?

If that doesn't work, can you please open Device Portal for the emulator (click the globe icon on the far right toolbar - second button from the bottom) and navigate to the System -> Device manager page.  On that page, expand "ACPI x64-based PC" then "Microsoft ACPI-Compliant System", "ACPI Module Device", "Microsoft Hyper-V Virtual Machine Bus" and finally "Microsoft Hyper-V Virtual PCI Bus".  Lastly, click on the cog next to "Microsoft Virtual Render Driver". Please copy-and-paste the "Properties" section up to and including the "StatusCode" line in your reply if possible.

**Comment by Noemata** [comment] 2019-10-15 01:56
Having the same issue with hardware acceleration using the 18362.1034 emulator on a Microsoft Surface Book 2!  The Surface Book 2 should always work given it's Microsoft's flagship hardware.  Doesn't work on any other system I've used the emulator on.  Disabling acceleration unblocks usage, but it's a real drag this sort of thing isn't getting tested properly.

**Comment by pbarnettms** [comment] 2019-10-15 21:32
@Noemata What version of Windows are you running on your Surface Book 2?  (You can find this by typing "ver" from a Command Prompt.).  In general, hardware acceleration works best on the Windows 10 May 2019 update (10.0.18362) or newer and with the latest drivers for your graphics chip.

**Comment by ArmsOfSorrow** [comment] 2019-10-16 16:54
@pbarnettms Here's the output:

Properties:
ID : PCI\VEN_1414&DEV_008E&SUBSYS_00000000&REV_00\5&32496F05&0&0
Description : Microsoft Virtual Render Driver
Class : Display
Manufacturer : Microsoft
StatusCode : 25191424
ProblemCode : 43

I'm running Radeon Software 19.9.3 right now; I'll try again after updating to 19.10.

**Comment by pbarnettms** [comment] 2019-10-16 20:16
@ArmsOfSorrow Thank you for the additional information.  We will investigate.  I'll update this thread when I have more information, though this will at a minimum likely be several days and more likely be longer than that.  Please continue to use the emulator with hardware graphics acceleration disabled.  If a newew driver for your graphics card becomes available, please do try it and let us know if it resolves your issue.

**Comment by dw-98** [comment] 2019-12-16 11:44
@pbarnettms @ArmsOfSorrow 
Is there any Update? Have the same issue, running a RX Vega 56 with the newest drivers..

**Comment by ArmsOfSorrow** [comment] 2019-12-19 20:23
I've tried again today, with emulator build 18362.1042 and Radeon Software 19.12.3.
No changes.

Here's the output again:
```
Properties:

ID : PCI\VEN_1414&DEV_008E&SUBSYS_00000000&REV_00\5&33BCC833&0&0

Description : Microsoft Virtual Render Driver

Class : Display

Manufacturer : Microsoft

StatusCode : 25191424

ProblemCode : 43
```

**Comment by pbarnettms** [comment] 2020-01-10 00:59
@ArmsOfSorrow The lack of any improvement with the newer build is unfortunately expected.  The issue is not expected to be resolved without a different update of either the Radeon driver or the Windows operating system on which you're running the emulator.  I'll provide more info when I have it, which will likely not be for several more weeks at least.

**Comment by ArmsOfSorrow** [comment] 2020-01-11 14:40
I have recently updated my PC to Windows 10.19041 and Radeon Software 20.1.1. No changes so far, but thanks for the heads up.

**Comment by pbarnettms** [comment] 2020-05-14 19:31
@ArmsOfSorrow If your PC has an Intel processor, can you please install the new 10.0.19041.1103 version of the HoloLens 2 Emulator and attempt to launch it.  Assuming you do not get hardware acceleration, can you please open Event Viewer and look under "Application and Services Logs" –> Microsoft –> Windows –> Dxgkrnl (Admin and Operational channels).  When the 19041 emulator is combined with the 19041 version of Windows on your desktop, you should see error events that give more information about why hardware acceleration is not working.

**Comment by ArmsOfSorrow** [comment] 2020-05-18 19:29
It works!

Emulator version 10.0.19041.1103 combined with Radeon Software 20.4.2 has working GPU acceleration. Very nice. 👍

**Comment by pbarnettms** [comment] 2020-05-18 20:25
Great to hear!  I'm going to close this issue.  Unfortunately we won't be able to go back and fix the older emulator builds, but please do let us know if you encounter any problems with this feature in the future.

**Closed by pbarnettms** 2020-05-18 20:25 UTC
