### ISSUE TITLE
what are the minimal packages needed for MRTK3 preview?

### ISSUE THREAD

**Issue by wfleming801** [MicrosoftDocs/mixed-reality#617] opened 2022-06-11 15:36 UTC
I see 13 packages under MRTK3, and I am not sure which ones to load. I want to load the very minimal to follow along the examples. For instance, which package provides the "MRTK3" menu option to appear in step 4-- "Edit Project Settings". Some combinations of packages are giving errors when loading, would be nice to know which packages play well for the preview. Could you add a recommended list of packages to start out with? thanks for your time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a45ca63-1167-32e9-02fa-0dc5bc7005fa
* Version Independent ID: 6a45ca63-1167-32e9-02fa-0dc5bc7005fa
* Content: [MRTK3 initial setup - Mixed Reality Toolkit](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/setup)
* Content Source: [mrtk-unity/mrtk3-overview/setup.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/mrtk3-overview/setup.md)
* Product: **mixed-reality**
* GitHub Login: @MaxWang-MS
* Microsoft Alias: **wangmax**

**Comment by MaxWang-MS** [comment] 2022-06-13 17:53
Hi @wfleming801, please refer to the [package overview page](https://docs.microsoft.com/windows/mixed-reality/mrtk-unity/mrtk3-overview/packages/packages-overview) for information on packages and then select the ones that fit your needs. When importing packages via the Mixed Reality Feature Tool, dependency management is automatically performed so you should not see errors. Please open let us know what packages you selected when you saw the errors.

**Comment by MaxWang-MS** [comment] 2022-06-13 17:59
We don't really have a recommended set of packages because we are going down the route of modularization and allowing you to choose. The menu item you mentioned is from Core Definitions, but by just importing that package alone there will not be a lot you can do. Most people would want the Input package and likely the UX packages, but again ultimately it depends on your needs.

**Comment by wfleming801** [comment] 2022-06-13 18:55
I chose all. Got errors. The. Tried a few subsets, got errors. Once I noticed the MRTK3 showed up in the project settings but I had errors, so it's unclear which package provides that text in the settings; I'm just wanting to get started and try out things, frustrating and time consuming to hunt and peck which packages work together to accomplish minimal preview.

**Comment by wfleming801** [comment] 2022-06-13 18:58
I'll add that even reading through the package descriptions, I don't know what I want. I want to be able to build a minimal project, I think it's great that there's modularity, but some guidance on a minimal set of packages would help me get to deployment faster.

**Comment by MaxWang-MS** [comment] 2022-06-13 19:00
@wfleming801 Can you let us know what errors you got? Maybe share a screenshot with us if possible.

**Comment by MaxWang-MS** [comment] 2022-06-13 19:06
Also can you clarify your definition of "a minimal project"? For example, deploying a scene with a static cube and no interaction needed has different packages requirements then deploying a scene with our ux components and interaction support.

**Comment by wfleming801** [comment] 2022-06-13 22:39
I'm wanting to try out "MRTK3" preview but am failing with selecting which of the 13(under MRTK3 heading) and/or other packages to load using the feature tool. I don't know what is needed; other than one of those packages puts "MRTK3" into the project settings -- would be nice to know which one does this, so that I can complete step 4. However, it would seem in order to go further, I will need additional packages. I don't know what packages are necessary for any of the demos-- even the simplest one of say "sample buttons"? I'd like to deploy the simplest demo, to understand full path from feature selection tool to on device deployment in order to demo 'MRTK3 features'.  Seems there's a gap in docs; that kinda drops you off at "here's all our packages, now go play" I'm spending a lot of my "off the clock" time revisiting this and trying to get the packages figured out. Would be nice to have a somewhat guided path to follow. I'll post the errors I've received along with package combinations; but there may be a delay in getting this detail.

**Comment by MaxWang-MS** [comment] 2022-06-15 02:02
Hi @wfleming801, on the [package overview page](https://docs.microsoft.com/windows/mixed-reality/mrtk-unity/mrtk3-overview/packages/packages-overview) there is a table showing which package contains what - for example if you need button prefabs, you should get the UX components package. Additionally if you are trying to deploy to an MR device then you would also need the input package. But by selecting those two (and the MROpenXR plugin as mentioned in the setup doc) you should have all you need (the feature tool will automatically include the dependencies of the packages you selected).
I was not able to reproduce the errors you mentioned (I chose all MRTK3 packages and imported them into a new project). Please share the ones you encountered at your earliest convenience so that we can look into it.

**Comment by cheles** [comment] 2022-06-20 14:07
@wfleming801  on top of what Max already mentioned, you'll probably need MRTK Input for object manipulation if that's what you want for step 4. Upon dragging MRTKProfile in Profile section, Unity will warn that you are missing some components, and that is MRTK Input
![image](https://user-images.githubusercontent.com/1419060/174619754-45e35c86-09c8-4c79-b448-a373c419564d.png)

**Comment by MaxWang-MS** [comment] 2022-11-17 00:42
Closing this issue as on the [setup page](https://learn.microsoft.com/windows/mixed-reality/mrtk-unity/mrtk3-overview/setup) we now provide recommendations for packages first-time users should choose.

**Closed by MaxWang-MS** 2022-11-17 00:42 UTC
Labels: mixed-reality/prod, Pri1
