### ISSUE TITLE
Broken link with regard to Text in Unity

### ISSUE THREAD

**Issue by SarahSexton** [MicrosoftDocs/mixed-reality#1292] opened 2019-06-18 14:13 UTC
**Existing document: "Text in Unity" docs.microsoft.com**
https://docs.microsoft.com/en-us/windows/mixed-reality/text-in-unity

**Broken:** Scroll to the bottom of the page to find a "See also" section linking to "Text Prefab in the MRTK". This link points to a 404 GitHub repo.
https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/mrtk_release/Assets/MixedRealityToolkit.SDK/StandardAssets/Prefabs/Text

Perhaps this is a problem with link validation, or use of absolute paths?

**Comment by jessemcculloch** [comment] 2019-06-19 13:58
Duplicate of Issue #1234, closing and tracking there.  Thanks @SarahSexton

**Closed** 2019-07-17 07:26 UTC
