### ISSUE TITLE
HoloLens 2 emulator build 10.0.19041.1103 is incompatible with AMD Ryzen processors

### ISSUE THREAD

**Issue by artob** [MicrosoftDocs/mixed-reality#2211] opened 2020-05-13 16:27 UTC
It would be helpful, in the interests of not wasting people's time, to mention on this page that nested virtualization is required to run the emulator (although it's not clear why?). And that since Hyper-V doesn't support nested virtualization except on Intel CPUs, the emulator will currently not run with AMD CPUs.

https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/nested-virtualization

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0051f2fd-9bcd-7eb8-48f0-b8b170d42a49
* Version Independent ID: 2c1a0a2b-6a3f-1a1d-caf1-4a06caf5411b
* Content: [Using the HoloLens Emulator - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-hololens-emulator#feedback)
* Content Source: [mixed-reality-docs/using-the-hololens-emulator.md](https://github.com/MicrosoftDocs/mixed-reality/blob/master/mixed-reality-docs/using-the-hololens-emulator.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @pbarnettms
* Microsoft Alias: **pbarnett**

**Comment by pbarnettms** [comment] 2020-05-13 16:38
@artob What error message(s) are you receiving trying to run the emulator?

**Comment by artob** [comment] 2020-05-13 16:55
@pbarnettms I get this error:

![2020-05-13](https://user-images.githubusercontent.com/4963/81841694-7ff7ec80-9553-11ea-8fd8-33dac25cbc5c.png)

This is on Windows 10 Pro build 18363 on physical hardware (AMD Ryzen 5 2600X) with all virtualization options enabled in the BIOS settings.

**Comment by artob** [comment] 2020-05-13 16:56
Related:

https://windowsserver.uservoice.com/forums/295047-general-feedback/suggestions/31734808-nested-virtualization-for-amd-epyc-and-ryzen

> Bruce commented  ·  February 12, 2020 00:43  ·  Flag as inappropriate
>
> Hello Hyper-V fans! I was recently alerted to your feedback on this topic and I hear your request loud and clear! I run the engineering team that is responsible for the Hyper-V hypervisor. I cannot commit to a specific Windows release that will support nested virtualization on an AMD CPU at the moment, but I recommend monitoring Windows insider builds for previews of this support as we push the changes into the hypervisor this year.

**Comment by pbarnettms** [comment] 2020-05-13 17:02
Thank you.  This is not expected.  We will investigate.

**Comment by pbarnettms** [comment] 2020-05-13 17:15
You mentioned on Slack that this didn't happen with the previous version.  Are you still able to launch that previous version even while the new version gives this error?  Which previous version do you have installed?

**Comment by artob** [comment] 2020-05-13 17:19
@pbarnettms You may have me confused with someone else. Which Slack channel are you referring to?

I've personally only tried HoloLens 2 Emulator build 10.0.19041.1103 on this hardware, and wouldn't expect the situation to improve with the older versions given Hyper-V's lack of nested virtualization support for AMD processors. (But willing to try that if you believe it's worthwhile.)

I still don't understand why nested virtualization is needed for the HoloLens emulator, though, when the emulator is hosted on physical hardware instead of a virtual machine. Are there actually two layers of virtualization involved?

**Comment by pbarnettms** [comment] 2020-05-13 17:23
@artob  I apologize - I saw a similar message on a Slack channel and thought it was you.  The HoloLens 2 Emulator does not require nested virtualization, which is why this is unexpected.  I suspect you would have success with older builds of the emulator (e.g., 10.0.18362.1061 - the May 2020 update for Windows Holographic version 1903), though obviously that won't have the new features.  If you are only looking to test our application on HoloLens 2, older HoloLens 2 Emulator versions may be a usable workaround until we understand why you're getting this error.

**Comment by artob** [comment] 2020-05-13 17:32
@pbarnettms Thanks for the clarification. OK, I will give a go with the older builds you suggest and report back tomorrow. (And if there's any other system information of potential usefulness that I can collect for you from this hardware, do let me know.)

**Comment by pbarnettms** [comment] 2020-05-13 19:57
@artob When you get the error with 10.0.19041.1103, does the error appear immediately when the emulator window appears, or does it look like the emulator is actually starting but then the error pops up a minute or two later?  Do you see "Loading ..." and then "OS is starting ..." and then get the error?

**Comment by artob** [comment] 2020-05-14 03:59
@pbarnettms The error pops up pretty much immediately after the emulator window appears. I don't see any other messages prior to the error, and I can't do anything (click on controls, etc) prior to the error.

**Comment by artob** [comment] 2020-05-14 06:56
> I suspect you would have success with older builds of the emulator (e.g., 10.0.18362.1061 - the May 2020 update for Windows Holographic version 1903), though obviously that won't have the new features.

@pbarnettms You were right. The 10.0.18362.1061 build boots up without issue:

![10 0 18362 1061](https://user-images.githubusercontent.com/4963/81902549-f420a780-95c8-11ea-83f1-c6062bf40329.png)

So, the reported problem is specific to the newer 10.0.19041.1103 build.

**Comment by pbarnettms** [comment] 2020-05-14 19:21
@artob Thanks for the confirmation.  We are investigating the issue with the 19041 build on AMD Ryzen processors.  I will update this thread when we have more info, though that may take a week or more.

**Comment by pbarnettms** [comment] 2020-05-20 19:17
@artob We have identified the cause of this and will plan to include the fix in the next official update.  To work around the issue until that update is available, in your Users\<username>\AppData\Local\Microsoft\XDE\HCS folder there will be a .json file for the emulator.  (The filename is randomly generated, and if you have multiple emulators installed there will be multiple files.)  One and only one of these files should have "ExposeVirtualizationExtensions" in it, and it should have a value of 'true'.  Change this to 'false' and your HoloLens 2 Emulator will launch.  This entry will not be set back to 'true' if you close and restart the emulator.

**Comment by artob** [comment] 2020-05-20 19:41
@pbarnettms Thanks, I'll try that workaround tomorrow 👍

**Comment by jessemcculloch** [comment] 2020-05-26 19:54
Thanks for your work on this @pbarnettms.  @artob, I'm going to close this issue at this time since it sounds like we have a work-around and a path forward with the next update.

**Closed by jessemcculloch** 2020-05-26 19:54 UTC
