### ISSUE TITLE
Cannot build Getting Started With Azure Spatial Anchors tutorial

### ISSUE THREAD

**Issue by camilador** [MicrosoftDocs/mixed-reality#2017] opened 2020-01-17 09:54 UTC
I get the following errors when trying to build the project following the "Getting Started With Azure Spatial Anchors" page https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-asa-ch1

Assets\AzureSpatialAnchors.SDK\Scripts\SpatialAnchorManager.cs(325,44): error CS0234: The type or namespace name 'SpatialPerceptionAccessStatus' does not exist in the namespace 'Microsoft.Windows.Perception.Spatial' (are you missing an assembly reference?)

Assets\AzureSpatialAnchors.SDK\Scripts\SpatialAnchorManager.cs(325,95): error CS0234: The type or namespace name 'SpatialAnchorExporter' does not exist in the namespace 'Microsoft.Windows.Perception.Spatial' (are you missing an assembly reference?)

Assets\AzureSpatialAnchors.SDK\Scripts\SpatialAnchorManager.cs(326,50): error CS0234: The type or namespace name 'SpatialPerceptionAccessStatus' does not exist in the namespace 'Microsoft.Windows.Perception.Spatial' (are you missing an assembly reference?)

Furthermore, if I close Unity and open it again, tons of new errors appear, where TextMeshPro and ARFoundation  are not recognized, in addition to errors of the type:
Assets\MixedRealityToolkit\Utilities\Gltf\Serialization\Importers\AssemblyInfo.cs(7,12): error CS0579: Duplicate 'AssemblyFileVersion' attribute
and similar...

I'm using Unity 2019.1.14f1, Visual Studio 2019, Windows 10 SDK 10.0.18362.0.

I would appreciate some help on how to resolve this.

**Comment by martinwilter** [comment] 2020-01-17 20:29
@camilador I believe this can be resolved by

Using MRTK 2.1.0 as currently specified in the [Importing the tutorial assets](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-asa-ch1#importing-the-tutorial-assets) section of the tutorial.

or

If you want to use MRTK 2.2.0, disable and completely remove MSBuild for Unity. Currently, there is no easy way to do that, so in this case, your best option might be to start over with a new Unity project and make sure you uncheck the MSBuild for Unity option before you apply the project settings using the MRTK Project Configurator:

![image](https://user-images.githubusercontent.com/16746283/72643734-39d3a900-3924-11ea-972f-abb5ab5fbd04.png)

**Comment by camilador** [comment] 2020-01-22 10:27
Thank you for the answer. I missed this when following the tutorial and was using the wrong package.
I now have a new issue in the last step of the multi-user tutorials series (5. Integrating Azure Spatial Anchors into a shared experience). 
The tutorial specifies to "select ShareAzureAnchorButton and move your attention to the Inspector panel. Scroll down to the drop-down menu shown in the image below, select AnchorModuleScript and click ShareAnchorNetwork()." However on my AnchorModuleScript there is not ShareAnchorNetwork() function present, I see the following ones
![Screenshot (3)](https://user-images.githubusercontent.com/55885187/72886196-a75b4d00-3d09-11ea-9000-f899fbfb2112.png)

Am I not using the right package?
I'm currently assigning SetAzureAnchorID to the Set Azure Anchor Button  and GetSharedAzureAnchorID to the Share Azure Anchor Button, photon seems to be working properly and I'm testing on 2 hololenses but the sessions are not in sync and the models are not positioned in the same locations.

**Comment by martinwilter** [comment] 2020-01-22 21:03
@camilador,

Thanks for reporting this and sorry for the inconvenience this caused you.

The issue you experienced seems to be caused by a missing file in the package named MRTK.HoloLens2.Unity.Tutorials.Assets.MultiUserCapabilities.2.1.0.1.unitypackage, this is now corrected.

Please download the package again:

[MRTK.HoloLens2.Unity.Tutorials.Assets.MultiUserCapabilities.2.1.0.1.unitypackage](https://github.com/microsoft/MixedRealityLearning/releases/download/multi-user-capabilities-v2.1.0.1/MRTK.HoloLens2.Unity.Tutorials.Assets.MultiUserCapabilities.2.1.0.1.unitypackage)

Then import only the AnchorModuleScript.cs:

![image](https://user-images.githubusercontent.com/16746283/72932882-784ad880-3d15-11ea-8169-876c9e334025.png)

The two previously missing functions, `ShareAnchorNetwork()` and `GetSharedAnchorNetwork()` should now be available.

**Closed** 2020-02-13 01:11 UTC
