### ISSUE TITLE
For the video its impossibel to view it, it says "This video is privat"

### ISSUE THREAD

**Issue by alexGreentown** [MicrosoftDocs/mixed-reality#663] opened 2022-10-07 15:27 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36ce5dc9-69a4-9264-d9ec-fe55866906aa
* Version Independent ID: 36ce5dc9-69a4-9264-d9ec-fe55866906aa
* Content: [How it works - Mixed Reality Capture Studios - Mixed Reality](https://learn.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/how-it-works-mixed-reality-capture-studios)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/how-it-works-mixed-reality-capture-studios.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/advanced-concepts/how-it-works-mixed-reality-capture-studios.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @mattzmsft
* Microsoft Alias: **mazeller**

**Comment by annebelleo** [comment] 2022-10-09 20:46
Duplicate of #642

**Closed** 2022-11-29 22:12 UTC
Labels: mixed-reality/prod, mr-dev/tech, Pri2
