### ISSUE TITLE
Packaging Failure

### ISSUE THREAD

**Issue by Eddiechui** [MicrosoftDocs/mixed-reality#133] opened 2020-11-24 07:43 UTC
When I was packaging my project, it shows an error in 'UxtPressableButtonActor.h' as below. Can anyone please advise?

UATHelper: Packaging (HoloLens):   C:/Users/eddie.chui/Documents/Unreal Projects/MyProject8/Plugins/UXTools/Source/UXTools/Public/Controls/UxtPressableButtonActor.h(106) : Error: Unrecognized type 'FUxtTextBrush' - type must be a UCLASS, USTRUCT or UENUM
PackagingResults: Error: Unrecognized type 'FUxtTextBrush' - type must be a UCLASS, USTRUCT or UENUM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba90317f-fc2e-1af2-dee1-b367368ea697
* Version Independent ID: 37bfc738-80d9-faba-f75e-0651a7b72b74
* Content: [5. Adding a button & resetting piece locations - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unreal/tutorials/unreal-uxt-ch5)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unreal/tutorials/unreal-uxt-ch5.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unreal/tutorials/unreal-uxt-ch5.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @hferrone
* Microsoft Alias: **v-hferrone**

**Comment by macborow** [comment] 2020-12-04 11:28
Hi @Eddiechui ! Apologies for the inconvenience. I see it has been over a week since you reported this issue and judging by another ticket you created I think you might have upgraded the project to use UXTools 0.10.0? Are you still experiencing this build issue or did it go away after the upgrade? In case the problem is still there, perhaps it could be fixed by removing all copies of UXTools from the Plugin directory and downloading UXTools 0.10.0 again? Thanks.

**Closed** 2020-12-04 17:34 UTC
