### ISSUE TITLE
Warnings when importing Azure Cloud Services Package

### ISSUE THREAD

**Issue by polar-kev** [MicrosoftDocs/mixed-reality#72] opened 2020-09-28 17:04 UTC
Unity 2019.4.10f1
MRTK 2.4

![image](https://user-images.githubusercontent.com/30964480/94463533-f51a3600-0171-11eb-9221-4986423ec604.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a45a901a-51fd-81b7-c2b9-22e78a7afeed
* Version Independent ID: 32b6e26d-280a-6239-a9bc-6f3bbe68c868
* Content: [Azure Cloud Tutorials - 1. Azure Cloud Services for HoloLens 2 - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-azure-01)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-azure-01.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-azure-01.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment] 2020-09-29 21:00
@polar-kev Which of the downloaded assets gives these warnings, or are there warnings in all of them? 
- Azure storage for Unity
- Azure Spatial Anchors
- MRTK.Tutorials.AzureCloudServices

**Comment by martinwilter** [comment] 2020-10-27 22:16
Hi @hferrone,

These warnings were from the MRTK.Tutorials.AzureCloudServices package and most of them were caused by the [SerializedField issue](https://issuetracker.unity3d.com/issues/serializedfield-fields-produce-field-is-never-assigned-to-dot-dot-dot-warning) which has been around for a long time. I've silenced all but three warnings from ASA SDK (v2.2.1).

Please merge in https://github.com/MicrosoftDocs/mixed-reality-pr/pull/2586, it updates the download links and adds a note informing readers they can ignore the three warnings. Thanks!

**Comment by martinwilter** [comment] 2020-11-04 22:43
Hi @hferrone, I believe this issue can be closed. (It was meant to be auto closed when PR merged in in the commit message).

**Closed** 2020-11-12 23:20 UTC
