### ISSUE TITLE
Azure Cloud Services tutorial error: Multiple Newtonsoft.Json.dll 

### ISSUE THREAD

**Issue by limsb95** [MicrosoftDocs/mixed-reality#407] opened 2021-08-17 06:40 UTC
Error Message: 
Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included or the current platform. Only one assembly with the same name is allowed per platform. (D:/ACS/Library/PackageCache/com.unity.nuget.newtonsoft-json@2.0.0/Runtime/Newtonsoft.Json.dll)
Multiple precompiled assemblies with the same name Newtonsoft.Json.dll included or the current platform. Only one assembly with the same name is allowed per platform. (Assets/Azure Storage/Plugins/Newtonsoft.Json.dll)

Steps to reproduce:
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-azure-01?tabs=openxr
Error occurs when importing tutorial assets:
AzureStorageForUnity.unitypackage
MRTK.Tutorials.AzureCloudServices.XRPlugginManagement.unitypackage

Unity : 2020.3.15f1
Mixed Reality Feature Tool for Unity : v1.0.2104.4 Beta
Mixed Reality Toolkit Foundation : 2.7.2
Mixed Reality OpenXR Plugin : 1.0.1
Windows 10 SDK 10.0.18362.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a45a901a-51fd-81b7-c2b9-22e78a7afeed
* Version Independent ID: 32b6e26d-280a-6239-a9bc-6f3bbe68c868
* Content: [Azure Cloud Services for HoloLens 2 - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-azure-01?tabs=openxr)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-azure-01.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-azure-01.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by bphillips09** [comment] 2021-08-17 21:29
Duplicate of #401

**Closed by bphillips09** 2021-08-17 21:29 UTC
