### ISSUE TITLE
Doing basic XRTK interactions using MRTK3 in VR scenarios?

### ISSUE THREAD

**Issue by ytehreem** [MicrosoftDocs/mixed-reality#657] opened 2022-09-27 14:15 UTC
Do MRTK3 has its own teleportation system, socket interaction etc. (like XR toolkit)?
In short, can we build VR scenarios using only MRTK3: telporting, grabbing, joining etc. (basic physical interactions)?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cf4a1898-af6b-be1b-4fa3-8c1269f855a9
* Version Independent ID: cf4a1898-af6b-be1b-4fa3-8c1269f855a9
* Content: [Mixed Reality Toolkit 3 Developer Documentation - MRTK3](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/)
* Content Source: [mrtk-unity/mrtk3-overview/index.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/mrtk3-overview/index.md)
* Product: **mixed-reality**
* GitHub Login: @MaxWang-MS
* Microsoft Alias: **wangmax**

**Comment by MaxWang-MS** [comment] 2022-10-05 02:23
Duplicate of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11050.

**Closed by MaxWang-MS** 2022-10-05 02:23 UTC
Labels: mixed-reality/prod, Pri1
