### ISSUE TITLE
Error when deploying on Hololens 2

### ISSUE THREAD

**Issue by AvaThalheim** [MicrosoftDocs/mixed-reality#184] opened 2021-02-02 08:39 UTC
I followed the Tutorial as described, yet i can not deploy the application to the Hololens 2. 
Visual Studio error:
Exection thrown at 0x000002AFE686F40 in MRTKSpatialAnchors.exe: 0xC0000005: Access violation executing location 0x000002AFE686F40

How can i resolve this issue? 
Any help is appreciated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b7f65b-2300-1e88-3072-5ecc28e5a8e5
* Version Independent ID: 2089610b-9581-ea9b-11c5-7be97e53c584
* Content: [Getting started with Azure Spatial Anchors - Mixed Reality](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-asa-02#feedback)
* Content Source: [mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md](https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-asa-02.md)
* Product: **mixed-reality**
* Technology: **mr-dev**
* GitHub Login: @jessemcculloch
* Microsoft Alias: **jemccull**

**Comment by hferrone** [comment] 2021-02-02 17:51
Closing this issue, as it's a duplicate of one we're actively tracking down - #183

**Closed by hferrone** 2021-02-02 17:51 UTC
