### ISSUE TITLE
HoloLens 2 Emulator input controls not working

### ISSUE THREAD

**Issue by danielputschoegl** [MicrosoftDocs/mixed-reality#1439] opened 2019-07-17 08:05 UTC
Similar problem to #1083 . I have no input controls in the emulator neither running as admin or not. Also running it from windows start menu as admin or not I have no input controls.

![image](https://user-images.githubusercontent.com/28919643/61356967-af789280-a877-11e9-8b2e-6add2bf54f2b.png)

The emulator worked fine after some troubleshooting the first day. Now working the second day with the emulator I've got this problem. Reinstalling the emulator didn't help.

**Comment by pbarnettms** [comment] 2019-07-17 22:49
@danielputschoegl Issue 1083 referenced a specific issue where connectivity works and then stops working, which has been root caused to a networking bug that will be resolved in a future update to Windows.  

For the issue you're encountering where connectivity does not work from the start, I see you've posted this issue on the Unity forum for Windows Mixed Reality as well (https://forum.unity.com/threads/hololens-2-emulator-input-controls-not-working.711713/#post-4758179).  We'll work through the issue there.  I'm going to close this item.

**Closed by pbarnettms** 2019-07-17 22:49 UTC
