### ISSUE TITLE
Shaders folder is missing if the Mixed Reality Feature Tool is used to import MRTK

### ISSUE THREAD

**Issue by spartan1047** [MicrosoftDocs/mixed-reality#237] opened 2021-03-16 03:46 UTC
I’m using the new Mixed Reality Feature Tool to create a new Unity project for HL2, I’m importing all latest and available Mixed Reality Toolkit features/packages, but when I go to the Unity Editor the Shaders folders is not part of the project, leading in the default pink used for missing shader.

I have made another project importing the foundation package (Microsoft.MixedReality.Toolkit.Unity.Foundation.2.6.1) by hand and everything works ok. 

Any Idea of how to solve this issue?, I’m encouraging the use of the MRFT in a project for the company I work for but if this is a mayor issue I think doing all by myself is the best workaround. 

![image](https://user-images.githubusercontent.com/15834155/111252019-e1ef0b80-85d5-11eb-95bb-6a558d94391e.png)
![image](https://user-images.githubusercontent.com/15834155/111252239-4c07b080-85d6-11eb-8f15-8e51a3e30ac8.png)

**Comment by polar-kev** [comment] 2021-03-16 22:51
@spartan1047, can you confirm that you created a completely fresh Unity project and aren't updating an older project?

@davidkline-ms, should the above have been covered by your addition of shaders to import logic https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9404?
Any idea what's happening here?

**Comment by davidkline-ms** [comment] 2021-03-16 22:54
The above should definitely have been covered. I will need to investigate.

Thanks @polar-kev!

@spartan1047 if you use Mixed Reality Toolkit > Utilities > Check for Shader Updates, does that get them copied into your project?

**Comment by spartan1047** [comment] 2021-03-17 03:37
Hello guys, thank you for the answers
@polar-kev Yes, I'm making a new Unity project from 0, I have created another one just to be sure that I was not making a mistake in the process. I'm having the same issue. 

@davidkline-ms If I use the "Check for Shader Updates" I get the following exception: 

> DirectoryNotFoundException: Could not find a part of the path 'C:\Users\CEdua\Documents\Unity Projects\Unity Playground\MRTK Test\Library\PackageCache\com.microsoft.mixedreality.toolkit.foundation@470e9fc4a9f2-1615852206097\SDK\Experimental\InteractiveElement\Examples\Scripts\CustomStateExample\KeyboardState'.
System.IO.__Error.WinIOError (System.Int32 errorCode, System.String maybeFullPath) (at <9577ac7a62ef43179789031239ba8798>:0)
System.IO.FileSystemEnumerableIterator`1[TSource].HandleError (System.Int32 hr, System.String path) (at <9577ac7a62ef43179789031239ba8798>:0)
System.IO.FileSystemEnumerableIterator`1[TSource].CommonInit () (at <9577ac7a62ef43179789031239ba8798>:0)
System.IO.FileSystemEnumerableIterator`1[TSource]..ctor (System.String path, System.String originalUserPath, System.String searchPattern, System.IO.SearchOption searchOption, System.IO.SearchResultHandler`1[TSource] resultHandler, System.Boolean checkHost) (at <9577ac7a62ef43179789031239ba8798>:0)
System.IO.FileSystemEnumerableFactory.CreateFileNameIterator (System.String path, System.String originalUserPath, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) (at <9577ac7a62ef43179789031239ba8798>:0)
System.IO.Directory.InternalGetFileDirectoryNames (System.String path, System.String userPathOriginal, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) (at <9577ac7a62ef43179789031239ba8798>:0)
System.IO.Directory.InternalGetFiles (System.String path, System.String searchPattern, System.IO.SearchOption searchOption) (at <9577ac7a62ef43179789031239ba8798>:0)
System.IO.Directory.GetFiles (System.String path, System.String searchPattern) (at <9577ac7a62ef43179789031239ba8798>:0)
System.IO.DirectoryInfo.GetFiles (System.String searchPattern) (at <9577ac7a62ef43179789031239ba8798>:0)
System.IO.DirectoryInfo.GetFilesSubdirs (System.Collections.ArrayList l, System.String pattern) (at <9577ac7a62ef43179789031239ba8798>:0)
(wrapper remoting-invoke-with-check) System.IO.DirectoryInfo.GetFilesSubdirs(System.Collections.ArrayList,string)
System.IO.DirectoryInfo.GetFilesSubdirs (System.Collections.ArrayList l, System.String pattern) (at <9577ac7a62ef43179789031239ba8798>:0)
(wrapper remoting-invoke-with-check) System.IO.DirectoryInfo.GetFilesSubdirs(System.Collections.ArrayList,string)
System.IO.DirectoryInfo.GetFilesSubdirs (System.Collections.ArrayList l, System.String pattern) (at <9577ac7a62ef43179789031239ba8798>:0)
(wrapper remoting-invoke-with-check) System.IO.DirectoryInfo.GetFilesSubdirs(System.Collections.ArrayList,string)
System.IO.DirectoryInfo.GetFilesSubdirs (System.Collections.ArrayList l, System.String pattern) (at <9577ac7a62ef43179789031239ba8798>:0)
(wrapper remoting-invoke-with-check) System.IO.DirectoryInfo.GetFilesSubdirs(System.Collections.ArrayList,string)
System.IO.DirectoryInfo.GetFilesSubdirs (System.Collections.ArrayList l, System.String pattern) (at <9577ac7a62ef43179789031239ba8798>:0)
(wrapper remoting-invoke-with-check) System.IO.DirectoryInfo.GetFilesSubdirs(System.Collections.ArrayList,string)
System.IO.DirectoryInfo.GetFilesSubdirs (System.Collections.ArrayList l, System.String pattern) (at <9577ac7a62ef43179789031239ba8798>:0)
(wrapper remoting-invoke-with-check) System.IO.DirectoryInfo.GetFilesSubdirs(System.Collections.ArrayList,string)
System.IO.DirectoryInfo.GetFilesSubdirs (System.Collections.ArrayList l, System.String pattern) (at <9577ac7a62ef43179789031239ba8798>:0)
(wrapper remoting-invoke-with-check) System.IO.DirectoryInfo.GetFilesSubdirs(System.Collections.ArrayList,string)
System.IO.DirectoryInfo.GetFilesSubdirs (System.Collections.ArrayList l, System.String pattern) (at <9577ac7a62ef43179789031239ba8798>:0)
(wrapper remoting-invoke-with-check) System.IO.DirectoryInfo.GetFilesSubdirs(System.Collections.ArrayList,string)
System.IO.DirectoryInfo.GetFilesSubdirs (System.Collections.ArrayList l, System.String pattern) (at <9577ac7a62ef43179789031239ba8798>:0)
System.IO.DirectoryInfo.GetFiles (System.String searchPattern, System.IO.SearchOption searchOption) (at <9577ac7a62ef43179789031239ba8798>:0)
(wrapper remoting-invoke-with-check) System.IO.DirectoryInfo.GetFiles(string,System.IO.SearchOption)
Microsoft.MixedReality.Toolkit.Utilities.Editor.OnLoadUtilities.FindShaderFolderInPackage () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.standardassets@928ca033d9bc-1615852199269/EditorUtilities/OnLoadUtilities.cs:152)
Microsoft.MixedReality.Toolkit.Utilities.Editor.OnLoadUtilities.EnsureShaders (System.Boolean bypassIgnore) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.standardassets@928ca033d9bc-1615852199269/EditorUtilities/OnLoadUtilities.cs:42)
Microsoft.MixedReality.Toolkit.Utilities.Editor.OnLoadUtilities..cctor () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.standardassets@928ca033d9bc-1615852199269/EditorUtilities/OnLoadUtilities.cs:23)
Rethrow as TypeInitializationException: The type initializer for 'Microsoft.MixedReality.Toolkit.Utilities.Editor.OnLoadUtilities' threw an exception.
System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor (System.RuntimeTypeHandle type) (at <9577ac7a62ef43179789031239ba8798>:0)
UnityEditor.EditorAssemblies.ProcessInitializeOnLoadAttributes (System.Type[] types) (at <2f1c602eae0d45c293fff3e3aef759fa>:0)

If you need more info I can create a video showing what I'm making and how I'm getting the issues. 

![image](https://user-images.githubusercontent.com/15834155/111409960-7bcdbb80-869d-11eb-88a6-8f7ff4434183.png)

**Comment by davidkline-ms** [comment] 2021-03-18 16:31
@spartan1047, that exception looks a bit odd to me. the shader update check should not involve the foundation package in any way.

i am working on trying to reproduce what you are seeing and will hopefully have an update for you soon.

**Comment by lazerwalker** [comment] 2021-03-18 16:44
FWIW, I'm having the same issue with MRTK 2.5.4. This is a brand new Unity project, using Unity 2019.4.16 and importing MRTK 2.5.4 via the Mixed Reality Feature Tool 1.0.2103 Beta. I've never seen materials render properly with this project; as soon as I drag in the Mesh prefabs for the first time, they're all pink.

There is no Mixed Reality Toolkit -> Utilities -> Check for Shader Updates option for me, and the "Upgrade MRTK Standard Shader for Lightweight Render Pipeline" option is grayed out.

**Comment by davidkline-ms** [comment] 2021-03-18 16:46
@lazerwalker , thanks for the info. the Check for Shader Updates is new to 2.6.x so i would not expect to see it in 2.5.4.

What version of Unity are you using?

**Comment by lazerwalker** [comment] 2021-03-18 16:47
As mentioned above, this is with 2019.4.16

**Comment by davidkline-ms** [comment] 2021-03-18 18:04
> As mentioned above

Haha! Thanks! I guess i need more coffee today 😄

**Comment by davidkline-ms** [comment] 2021-03-18 18:05
FYI: Work on this issue is being tracked on the MRTK repository https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9527

**Comment by davidkline-ms** [comment] 2021-03-18 18:18
@spartan1047, i think i may know what is happening on your machine.  Unity has a path length limit of 255 characters. The following message from the exception (i took a second look) points to that as potentially being the root cause:

```
C:\Users\CEdua\Documents\Unity Projects\Unity Playground\MRTK Test\Library\PackageCache\com.microsoft.mixedreality.toolkit.foundation@470e9fc4a9f2-1615852206097\SDK\Experimental\InteractiveElement\Examples\Scripts\CustomStateExample\KeyboardState
```

In general, Unity does not execute script code if there are compilation issues (such as would occur with a very long path). 

Could you please try a project with a short (ex: c:\test\MRTKTest) path and see if the shader copy completes properly?

Thanks!

**Comment by davidkline-ms** [comment] 2021-03-18 18:19
@lazerwalker, do you have any script compile errors in the console for your project?

**Comment by lazerwalker** [comment] 2021-03-18 20:44
@davidkline-ms I get the following warning at runtime, which seems specific to the visual profiler:

```
A shader supporting instancing could not be found for the VisualProfiler, falling back to traditional rendering. This may impact performance.
UnityEngine.Debug:LogWarning(Object)
Microsoft.MixedReality.Toolkit.Diagnostics.MixedRealityToolkitVisualProfiler:Reset() (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@42d97e164c04-1616004912136/Services/DiagnosticsSystem/MixedRealityToolkitVisualProfiler.cs:247)
Microsoft.MixedReality.Toolkit.Diagnostics.MixedRealityToolkitVisualProfiler:Start() (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@42d97e164c04-1616004912136/Services/DiagnosticsSystem/MixedRealityToolkitVisualProfiler.cs:286)
```

There are no compile-time errors.

I'm relatively confident I'm not hitting a path length limit issue, but I'm going to try moving the project closer to root as well just to be sure, will update.

**Comment by lazerwalker** [comment] 2021-03-18 21:40
For the record, manually importing the MRTK Foundation 2.5.4 `.unitypackage` right on top of the broken copy fixed my rendering issues.

Still happy to help debug however I can, and would still love to see this fixed with 2.5.4 -- my team is recommending people use the MRFT in a MS Docs quickstart, and I would prefer to not need to adjust that.

**Comment by davidkline-ms** [comment] 2021-03-18 22:15
@lazerwalker,

MRTK 2.6.x took a change to how shader copies are made (and provides the Check for Shader Updates menu item).

If you could try creating a new project using 2.6.0 or 2.6.1 and let me know your results, it would be SUPER helpful, Thanks!

**Comment by spartan1047** [comment] 2021-03-18 22:17
@lazerwalker I have made a new proyect in C:/UnityProject and everything works fine now, thank you for the suggesitons.

**Closed** 2021-03-23 18:03 UTC
